sudo: required
dist: trusty
language: cpp
cache: apt
os:
 - linux
compiler:
 - gcc
install:
 - sudo apt-get update -q && sudo apt-get upgrade -yqq && ./bootstrap_linux.sh
script:
 - cd build && make -j4
notifications:
  slack:
    secure: g1Nm7C7TYKg4RjDJ5cwuEcgKXfOAmVOu51adTPLBLGzZcCbCrkwQgI39ZycsalaACSnC8iNvqSCbRfZIA5mkDZ7VADaiZgLoWjq3RQzJmWgwGhhtyRkbtiicBnowTL5hIEiMOv6RnKlbB7M2OwzRiS07+FQXrK24hz+qm6zPptw=
